CC=g++
exe=GC


$menu:
	 $(CC) -lSDL2  ../menu_functions/menuHelpers.cpp ../../clunky_gl/clunkyCore.c ../../clunky_gl/clunkyAdvancedCollisions.c ../../clunky_gl/clunkyEventElements.c ../../clunky_gl/clunkyHash.c  ../menu_functions/generalHelpers.cpp  ../menu_functions/menu.cpp testGameOver.cpp -o gameOver_ex -w
