CC=g++
exe=GC


$menu:
	 $(CC) -lSDL2 menuHelpers.cpp ../clunky_gl/clunkyCore.c ../clunky_gl/clunkyAdvancedCollisions.c ../clunky_gl/clunkyEventElements.c ../clunky_gl/clunkyHash.c generalHelpers.cpp menu.cpp menu_ex.cpp -o menu_ex -w
