CC=gcc
exe=GC


$menu:
	 $(CC) -lSDL2 clunkyCore.c clunkyAdvancedCollisions.c clunkyAdvEvents.c clunkyHash.c menu_ex.c -o menu_ex

$(exe):
	$(CC) -lSDL2 clunkyCore.c grannyCrumpet.c clunkyAdvEvents.c clunkyHash.c clunkyAdvancedCollisions.c -o $(exe)
