CC=g++
exe=GC


$menu:
	 $(CC) -lSDL2 clunkyCore.c clunkyAdvancedCollisions.c clunkyAdvEvents.c clunkyHash.c menu_ex.cpp -o menu_ex -w

$(exe):
	$(CC) -lSDL2 clunkyCore.c grannyCrumpet.c clunkyAdvEvents.c clunkyHash.c clunkyAdvancedCollisions.c -o $(exe)
