CC=g++
exe=GC


$menu:
	 $(CC) -lSDL2 gameCore.cpp ship.c ./menu_functions/menuHelpers.cpp ../clunky_gl/clunkyCore.c ../clunky_gl/clunkyAdvancedCollisions.c ../clunky_gl/clunkyEventElements.c ../clunky_gl/clunkyHash.c  ./menu_functions/generalHelpers.cpp  ./menu_functions/menu.cpp  ./menu_functions/getGameParameters.cpp battleship.cpp -o battleship_ex -w
