CC=g++
exe=GC

$menu:
	 $(CC) -lSDL2 aiBoards.c bsCore.c gameCore.cpp ship.c ./menu_functions/menuHelpers.cpp ../clunky_gl/clunkyCore.c ../clunky_gl/clunkyAdvancedCollisions.c ../clunky_gl/clunkyEventElements.c ../clunky_gl/clunkyHash.c  ./menu_functions/generalHelpers.cpp  ./menu_functions/menu.cpp  ./menu_functions/getGameParameters.cpp ./pause_menu/pauseMenu.cpp battleship.cpp ./game_over/data_functions/enterScore.cpp ./game_over/data_functions/getHighScores.cpp ./game_over/data_functions/writeScores.cpp ./game_over/gameOver.cpp ./game_over/name_input/inputName.cpp -o battleship_ex -w
